name: "Chris' Thoughts"
favicon: null
layout_spectrum: 0.8128890416119248
typography_spectrum: 0.8035955941304564
title: "Chris' Thoughts"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.2060137924272567
  lightness: 0.6249031180050224
  saturation: 0.7306739168707281
  rhythmicContrast: 0.6544149820692837
purpose: []
