name: "Chris' Thoughts"
favicon: null
layout_spectrum: 0.74953
typography_spectrum: 0.36956
title: "Chris' Thoughts"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#8d4716'
    - '#e47734'
    - '#ffa67e'
    - '#ffebd6'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
