typography_spectrum: 0.36956
color:
  brandColors:
    - '#123e57'
    - '#276689'
    - '#fafafa'
    - '#4bbbfa'
    - '#7cd9fb'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74953
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Christophe Druet
  email: christophe@druet.be
  url: 'http://christophedruet.com'
name: "Chris' Thoughts"
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: "Chris' Thoughts"
purpose: []
