name: "Chris' Thoughts"
favicon: null
layout_spectrum: 0.74953
typography_spectrum: 0.36956
title: "Chris' Thoughts"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#123e57'
    - '#276689'
    - '#fafafa'
    - '#4bbbfa'
    - '#7cd9fb'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
